# Generated by Django 5.2.7 on 2025-11-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='afd_state',
            field=models.CharField(default='q0', help_text='Estado final del autómata (q0, q1, q2, q3)', max_length=10, verbose_name='Estado del AFD'),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='detected_words',
            field=models.JSONField(default=list, help_text='Lista de palabras/frases detectadas con sus posiciones y tipos', verbose_name='Palabras detectadas'),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='highlighted_text',
            field=models.TextField(blank=True, help_text='Texto con palabras tóxicas resaltadas en HTML', verbose_name='Texto resaltado'),
        ),
        migrations.AlterField(
            model_name='textanalysis',
            name='toxicity_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('low', 'Low'), ('medium', 'Medium'), ('extreme', 'Extreme')], default='safe', help_text='Nivel de toxicidad detectado', max_length=20, verbose_name='Nivel de toxicidad'),
        ),
        migrations.AlterField(
            model_name='toxicpattern',
            name='toxicity_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('low', 'Low'), ('medium', 'Medium'), ('extreme', 'Extreme')], default='low', help_text='Nivel de toxicidad asignado a este patrón', max_length=20, verbose_name='Nivel de toxicidad'),
        ),
    ]
