# Generated by Django 5.2.7 on 2025-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_textanalysis_afd_state_textanalysis_detected_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='source_type',
            field=models.CharField(choices=[('text', 'Texto ingresado'), ('file', 'Archivo adjunto')], default='text', max_length=10, verbose_name='Origen del contenido'),
        ),
    ]
